apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

configMapGenerator:
- name: environment-variables
  envs: [environment-properties.env]
  behavior: create

replacements:
- source:
    kind: ConfigMap
    name: environment-variables
    fieldPath: data.METALLB_IP_RANGE
  targets:
  - select:
      name: example
      kind: IPAddressPool
    fieldPaths:
    - spec.addresses.0


resources:
- 00-metallb-native.yaml
- 01-metallb-config.yaml
#  
#  - 01-install.yaml
#  - 02-ingress.yaml