apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  # The name here doesn't matter.
  name: external-secrets
name: external-secrets
# The name of the release
releaseName: external-secrets
# Path to a values.yaml
valuesFile: values.yaml
# Namespace to deploy to
releaseNamespace: external-secrets
# URL to the Repo
repo: https://charts.external-secrets.io
